name: Daily Python Script

# Controls when the workflow will run
on:
  schedule:
    # Runs every day at 5:45 PM Egypt time (2:45 PM UTC)
    - cron: '01 15 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Check out the code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.3'

    # Install dependencies if you have a requirements.txt file
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Run your script
    - name: Run Python script
      run: |
        python main.py
