name: Daily Python Script

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

on:
  schedule: 
    # Runs daily at 10 PM Kuwait time (7 PM UTC)
    - cron: '57 13 * * *'  # Adjust this as needed for scheduling

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate  # On Windows, use `venv\Scripts\activate`
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Activate virtual environment
      run: |
        source venv/bin/activate


    # Run your script
    - name: Run Python script
      run: |
        python main.py
