name: Daily Python Script

# Controls when the workflow will run
on:
  schedule:
    # Runs every day at 6:06 PM Egypt time (4:06 PM UTC)
    - cron: '21 16 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Check out the code
      uses: actions/checkout@v3

    # Run your script
    - name: Run Python script
      run: |
        python main.py
